name = "VSOP87"
uuid = "96062bd6-7aaa-4016-af0e-b09ea08f9cbc"
authors = ["Mike Kretlow <mikekretlow@gmail.com>"]
keywords = ["astronomy"]
desc = "VSOP87 ephemeris"
license = "MIT"
version = "0.1.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
